#!/bin/bash

vimrc="./.vimrc"
bak_flag=0

if [ -f $vimrc ]
then
    echo "Another vimrc is already installed"
    echo "Do you want to make a backup file for original file? (y/n)"

    read input

    if [ "$input" == "y" ]
    then
        echo "making backup file..."
        mv ~/.vimrc ~/.vimrc.bak
        echo "done"
        bak_flag=1
    else
        echo "Do you want to delete original file? y for delete, n for quit. (y/n)"

        read input

        if [ "$input" == "y" ]
        then
            echo "deleting original file..."
            rm -f ~/.vimrc
            echo "done"
        else
            exit 0
        fi
    fi
fi

if [ bak_flag ]
then
    echo "Your backup file is in ~/.vimrc.bak"
fi
echo "installation completed"

cp -r ./.vim ~/
cp ./.vimrc ~/

exit 0
