#!/bin/bash

bak_flag=0

if [[ -f $HOME/.vimrc ]]; then
    echo "Another vimrc is already installed"
    echo "Do you want to make a backup file for original file? (Y/n)"

    input="Y"
    read input

    if [[ $input =~ ^(y|Y)(es)?$ ]]; then
        echo "making backup file..."
        mv ~/.vimrc ~/.vimrc~
        if [[ -d $HOME/.vim ]]; then
            mv ~/.vim ~/.vim~
        fi
        echo "done"
        bak_flag=1
    else
        echo "Do you want to delete original file? y for delete, n for quit. (y/N)"

        input="N"
        read input

        if [[ $input =~ ^(y|Y)(es)?$ ]]; then
            echo "deleting original file..."
            rm ~/.vimrc
            if [[ -d $HOME/.bash ]]; then
                rm -r ~/.vim
            fi
            echo "done"
        else
            exit 0
        fi
    fi
fi

if [[ $bak_flag == 1 ]]; then
    echo "Your backup file is in ~/.vimrc~"
fi

cp -r ./.vim ~/
cp ./.vimrc ~/

echo "installation completed"
exit 0
