#!/bin/bash

bak_flag=0

if [[ -f $HOME/.tmux.conf ]]; then
    echo "Another tmux.conf already exists"
    echo "Do you want to make backup file for original? (Y/n)"

    input="Y"
    read input

    if [[ $input =~ ^(y|Y)(es)?$ ]]; then
        echo "making backup file..."
        mv ~/.tmux.conf ~/.tmux.conf~
        echo "done"
        bak_flag=1
    else
        echo "Do you want to delete original file? y for delete, n for quit. (y/N)"

        input="N"
        read input
        
        if [[ $input =~ ^(y|Y)(es)?$ ]]; then
            echo "deleting original file..."
            rm -f ~/.tmux.conf
            echo "done"
        else
            exit 0
        fi
    fi
fi

if [[ $bak_flag == 1 ]]; then
    echo "Your backup file is in ~/.tmux.conf~"
fi

cp ./.tmux.conf ~/

echo "installation completed"
exit 0
