#!/bin/bash

bak_flag=0

if [[ -f $HOME/.bashrc ]]; then
    echo "Another bashrc is already installed"
    echo "Do you want to make a backup file for original file? (Y/n)"

    input="Y"
    read input

    if [[ $input =~ "^y(es)?$" || $input =~ "^Y(ES)?$" ]]; then
        echo "making backup file..."
        mv ~/.bashrc ~/.bashrc~
        if [[ -d $HOME/.bash ]]; then
            mv ~/.bash ~/.bash~
        fi
        echo "done"
        bak_flag=1
    else
        echo "Do you want to delete original file? y for delete, n for quit. (y/N)"

        input="N"
        read input

        if [[ $input =~ "^y(es)?$" || $input =~ "^Y(ES)?$" ]]
        then
            echo "deleting original file..."
            rm ~/.bashrc
            if [[ -d $HOME/.bash ]]; then
                rm -r ~/.bash
            fi
            echo "done"
        else
            exit 0
        fi
    fi
fi

if [[ $bak_flag == 1 ]]; then
    echo "Your backup file is in ~/.bashrc~"
fi

cp -r ./.bash ~/
cp ./.bashrc ~/

echo "installation completed"
exit 0
